[package]
name = "realtime-rs"
version = "0.1.0"
edition = "2021"
description = "A rust implementation of the supabase realtime client library."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
